# Generated by Django 6.0.7 on 2026-08-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
