# Generated by Django 6.0.7 on 2026-08-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tickets.ticketcomment'),
        ),
    ]
