# Generated by Django 6.0.7 on 2026-08-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketcomment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_color',
            field=models.CharField(default='#0052cc', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='header_color',
            field=models.CharField(default='#85b8ff', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
