# Generated by Django 6.0.7 on 2026-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_userprofile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team Vatana', max_length=100)),
                ('icon_type', models.CharField(default='preset', max_length=20)),
                ('icon_value', models.CharField(default='mountains', max_length=255)),
                ('icon_bg_color', models.CharField(default='#0052cc', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Setting',
                'verbose_name_plural': 'Team Settings',
                'db_table': 'team_settings',
            },
        ),
    ]
