# Generated by Django 6.0.7 on 2026-08-18 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_update_ticket_codes_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsetting',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teamsetting',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamsetting',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamsetting',
            name='space_type',
            field=models.CharField(default='Team-managed software', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.teamsetting'),
        ),
    ]
